-- REVERSA de limpieza_columnas_muertas.sql (recrea las columnas con su definición original; los datos de kmini/odometerini están en device_bak_20261006)
USE gts;

ALTER TABLE device
  ADD COLUMN `equipmentStatus` int(11) NULL DEFAULT NULL AFTER `equipmentType`,
  ADD COLUMN `vehicleMake` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `equipmentStatus`,
  ADD COLUMN `vehicleModel` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `vehicleMake`,
  ADD COLUMN `driverStatus` int(10) unsigned NULL DEFAULT NULL AFTER `driverID`,
  ADD COLUMN `fuelCapacity` double NULL DEFAULT NULL AFTER `driverStatus`,
  ADD COLUMN `fuelEconomy` double NULL DEFAULT NULL AFTER `fuelCapacity`,
  ADD COLUMN `planDistanceKM` double NULL DEFAULT NULL AFTER `speedLimitKPH`,
  ADD COLUMN `installTime` int(10) unsigned NULL DEFAULT NULL AFTER `planDistanceKM`,
  ADD COLUMN `resetTime` int(10) unsigned NULL DEFAULT NULL AFTER `installTime`,
  ADD COLUMN `expirationTime` int(10) unsigned NULL DEFAULT NULL AFTER `resetTime`,
  ADD COLUMN `deviceType` varchar(24) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `deviceCode`,
  ADD COLUMN `pushpinID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `deviceType`,
  ADD COLUMN `displayColor` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `pushpinID`,
  ADD COLUMN `simID` varchar(24) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `simPhoneNumber`,
  ADD COLUMN `ignitionIndex` smallint(6) NULL DEFAULT NULL AFTER `dataKey`,
  ADD COLUMN `codeVersion` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `ignitionIndex`,
  ADD COLUMN `featureSet` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `codeVersion`,
  ADD COLUMN `ipAddressValid` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `featureSet`,
  ADD COLUMN `lastDuplexConnectTime` int(10) unsigned NULL DEFAULT NULL AFTER `lastTotalConnectTime`,
  ADD COLUMN `pendingPingCommand` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastDuplexConnectTime`,
  ADD COLUMN `lastPingTime` int(10) unsigned NULL DEFAULT NULL AFTER `pendingPingCommand`,
  ADD COLUMN `totalPingCount` smallint(5) unsigned NULL DEFAULT NULL AFTER `lastPingTime`,
  ADD COLUMN `maxPingCount` smallint(5) unsigned NULL DEFAULT NULL AFTER `totalPingCount`,
  ADD COLUMN `commandStateMask` int(10) unsigned NULL DEFAULT NULL AFTER `maxPingCount`,
  ADD COLUMN `expectAck` tinyint(4) NULL DEFAULT NULL AFTER `commandStateMask`,
  ADD COLUMN `expectAckCode` int(10) unsigned NULL DEFAULT NULL AFTER `expectAck`,
  ADD COLUMN `lastAckCommand` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `expectAckCode`,
  ADD COLUMN `lastAckTime` int(10) unsigned NULL DEFAULT NULL AFTER `lastAckCommand`,
  ADD COLUMN `dcsPropertiesID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastAckTime`,
  ADD COLUMN `dcsConfigMask` int(10) unsigned NULL DEFAULT NULL AFTER `dcsPropertiesID`,
  ADD COLUMN `dcsConfigString` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `dcsConfigMask`,
  ADD COLUMN `dcsCommandHost` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `dcsConfigString`,
  ADD COLUMN `supportsDMTP` tinyint(4) NULL DEFAULT NULL AFTER `dcsCommandHost`,
  ADD COLUMN `unitLimitInterval` smallint(5) unsigned NULL DEFAULT NULL AFTER `supportedEncodings`,
  ADD COLUMN `maxAllowedEvents` smallint(5) unsigned NULL DEFAULT NULL AFTER `unitLimitInterval`,
  ADD COLUMN `totalProfileMask` blob NULL DEFAULT NULL AFTER `maxAllowedEvents`,
  ADD COLUMN `totalMaxConn` smallint(5) unsigned NULL DEFAULT NULL AFTER `totalProfileMask`,
  ADD COLUMN `totalMaxConnPerMin` smallint(5) unsigned NULL DEFAULT NULL AFTER `totalMaxConn`,
  ADD COLUMN `duplexProfileMask` blob NULL DEFAULT NULL AFTER `totalMaxConnPerMin`,
  ADD COLUMN `duplexMaxConn` smallint(5) unsigned NULL DEFAULT NULL AFTER `duplexProfileMask`,
  ADD COLUMN `duplexMaxConnPerMin` smallint(5) unsigned NULL DEFAULT NULL AFTER `duplexMaxConn`,
  ADD COLUMN `lastTcpSessionID` varchar(180) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `duplexMaxConnPerMin`,
  ADD COLUMN `listenPortCurrent` smallint(5) unsigned NULL DEFAULT NULL AFTER `remotePortCurrent`,
  ADD COLUMN `lastOutputState` int(10) unsigned NULL DEFAULT NULL AFTER `lastInputState`,
  ADD COLUMN `lastFuelLevel` double NULL DEFAULT NULL AFTER `lastBatteryLevel`,
  ADD COLUMN `lastFuelTotal` double NULL DEFAULT NULL AFTER `lastFuelLevel`,
  ADD COLUMN `lastOilLevel` double NULL DEFAULT NULL AFTER `lastFuelTotal`,
  ADD COLUMN `lastDistanceKM` double NULL DEFAULT NULL AFTER `lastCellServingInfo`,
  ADD COLUMN `lastIgnitionHours` double NULL DEFAULT NULL AFTER `lastIgnitionOffTime`,
  ADD COLUMN `lastMalfunctionLamp` tinyint(4) NULL DEFAULT NULL AFTER `lastStartTime`,
  ADD COLUMN `lastFaultCode` varchar(96) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastMalfunctionLamp`,
  ADD COLUMN `lastNotifyTime` int(10) unsigned NULL DEFAULT NULL AFTER `allowNotify`,
  ADD COLUMN `lastNotifyCode` int(10) unsigned NULL DEFAULT NULL AFTER `lastNotifyTime`,
  ADD COLUMN `lastNotifyRule` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastNotifyCode`,
  ADD COLUMN `notifyEmail` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastNotifyRule`,
  ADD COLUMN `notifySelector` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `notifyEmail`,
  ADD COLUMN `notifyDescription` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `notifyAction`,
  ADD COLUMN `notifySubject` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `notifyDescription`,
  ADD COLUMN `notifyText` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `notifySubject`,
  ADD COLUMN `notifyUseWrapper` tinyint(4) NULL DEFAULT NULL AFTER `notifyText`,
  ADD COLUMN `notifyPriority` smallint(5) unsigned NULL DEFAULT NULL AFTER `notifyUseWrapper`,
  ADD COLUMN `parkedLatitude` double NULL DEFAULT NULL AFTER `notifyPriority`,
  ADD COLUMN `parkedLongitude` double NULL DEFAULT NULL AFTER `parkedLatitude`,
  ADD COLUMN `parkedRadius` double NULL DEFAULT NULL AFTER `parkedLongitude`,
  ADD COLUMN `assignedUserID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `parkedRadius`,
  ADD COLUMN `thermalProfile` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `assignedUserID`,
  ADD COLUMN `hoursOfOperation` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `thermalProfile`,
  ADD COLUMN `activeCorridor` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `lastEventsPerSecondMS`,
  ADD COLUMN `fixedLatitude` double NULL DEFAULT NULL AFTER `activeCorridor`,
  ADD COLUMN `fixedLongitude` double NULL DEFAULT NULL AFTER `fixedLatitude`,
  ADD COLUMN `fixedAddress` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `fixedLongitude`,
  ADD COLUMN `fixedContactPhone` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `fixedAddress`,
  ADD COLUMN `fixedServiceTime` int(10) unsigned NULL DEFAULT NULL AFTER `fixedContactPhone`,
  ADD COLUMN `linkURL` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `fixedServiceTime`,
  ADD COLUMN `linkDescription` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `linkURL`,
  ADD COLUMN `lastBorderCrossTime` int(10) unsigned NULL DEFAULT NULL AFTER `borderCrossing`,
  ADD COLUMN `maintIntervalKM0` double NULL DEFAULT NULL AFTER `lastBorderCrossTime`,
  ADD COLUMN `maintOdometerKM0` double NULL DEFAULT NULL AFTER `maintIntervalKM0`,
  ADD COLUMN `maintIntervalKM1` double NULL DEFAULT NULL AFTER `maintOdometerKM0`,
  ADD COLUMN `maintOdometerKM1` double NULL DEFAULT NULL AFTER `maintIntervalKM1`,
  ADD COLUMN `maintIntervalHR0` double NULL DEFAULT NULL AFTER `maintOdometerKM1`,
  ADD COLUMN `maintEngHoursHR0` double NULL DEFAULT NULL AFTER `maintIntervalHR0`,
  ADD COLUMN `maintNotes` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `maintEngHoursHR0`,
  ADD COLUMN `reminderMessage` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `maintNotes`,
  ADD COLUMN `reminderInterval` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `reminderMessage`,
  ADD COLUMN `reminderTime` int(10) unsigned NULL DEFAULT NULL AFTER `reminderInterval`,
  ADD COLUMN `lastServiceTime` int(10) unsigned NULL DEFAULT NULL AFTER `reminderTime`,
  ADD COLUMN `nextServiceTime` int(10) unsigned NULL DEFAULT NULL AFTER `lastServiceTime`,
  ADD COLUMN `workOrderID` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `nextServiceTime`,
  ADD COLUMN `jobNumber` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `workOrderID`,
  ADD COLUMN `jobLatitude` double NULL DEFAULT NULL AFTER `jobNumber`,
  ADD COLUMN `jobLongitude` double NULL DEFAULT NULL AFTER `jobLatitude`,
  ADD COLUMN `jobRadius` double NULL DEFAULT NULL AFTER `jobLongitude`,
  ADD COLUMN `lastDataPushTime` int(10) unsigned NULL DEFAULT NULL AFTER `customAttributes`,
  ADD COLUMN `lastEventCreateMillis` bigint(20) NULL DEFAULT NULL AFTER `lastDataPushTime`,
  ADD COLUMN `tiempoorigen` int(10) NULL DEFAULT NULL AFTER `rutaact`,
  ADD COLUMN `configtime` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `uniprox`,
  ADD COLUMN `odometercontrol` double NULL DEFAULT NULL AFTER `timeuniprox`,
  ADD COLUMN `codmantenimiento` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `odometercontrol`,
  ADD COLUMN `msjpbruscas` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0' AFTER `fecasignacion`,
  ADD COLUMN `msjdesconexion` varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0' AFTER `msjpbruscas`,
  ADD COLUMN `odometerini` double NULL DEFAULT NULL AFTER `msjdesconexion`,
  ADD COLUMN `kmini` double NULL DEFAULT NULL AFTER `odometerini`,
  ADD INDEX `notifyTime` (`lastNotifyTime`);

ALTER TABLE eventdata
  ADD COLUMN `transportID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `altitude`,
  ADD COLUMN `inputMask` int(10) unsigned NULL DEFAULT NULL AFTER `transportID`,
  ADD COLUMN `outputMask` int(10) unsigned NULL DEFAULT NULL AFTER `inputMask`,
  ADD COLUMN `seatbeltMask` int(10) unsigned NULL DEFAULT NULL AFTER `outputMask`,
  ADD COLUMN `odometerOffsetKM` double NULL DEFAULT NULL AFTER `odometerKM`,
  ADD COLUMN `geozoneIndex` int(10) unsigned NULL DEFAULT NULL AFTER `odometerOffsetKM`,
  ADD COLUMN `geozoneID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `geozoneIndex`,
  ADD COLUMN `streetAddress` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `creationTime`,
  ADD COLUMN `stateProvince` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `city`,
  ADD COLUMN `postalCode` varchar(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `stateProvince`,
  ADD COLUMN `subdivision` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `country`,
  ADD COLUMN `speedLimitKPH` double NULL DEFAULT NULL AFTER `subdivision`,
  ADD COLUMN `isTollRoad` tinyint(4) NULL DEFAULT NULL AFTER `speedLimitKPH`,
  ADD COLUMN `gpsFixStatus` int(10) unsigned NULL DEFAULT NULL AFTER `gpsFixType`,
  ADD COLUMN `horzAccuracy` double NULL DEFAULT NULL AFTER `gpsFixStatus`,
  ADD COLUMN `vertAccuracy` double NULL DEFAULT NULL AFTER `horzAccuracy`,
  ADD COLUMN `HDOP` double NULL DEFAULT NULL AFTER `vertAccuracy`,
  ADD COLUMN `fuelPressure` double NULL DEFAULT NULL AFTER `signalStrength`,
  ADD COLUMN `fuelUsage` double NULL DEFAULT NULL AFTER `fuelPressure`,
  ADD COLUMN `fuelTemp` double NULL DEFAULT NULL AFTER `fuelUsage`,
  ADD COLUMN `fuelLevel` double NULL DEFAULT NULL AFTER `fuelTemp`,
  ADD COLUMN `fuelLevel2` double NULL DEFAULT NULL AFTER `fuelLevel`,
  ADD COLUMN `fuelEconomy` double NULL DEFAULT NULL AFTER `fuelLevel2`,
  ADD COLUMN `fuelTotal` double NULL DEFAULT NULL AFTER `fuelEconomy`,
  ADD COLUMN `fuelRemain` double NULL DEFAULT NULL AFTER `fuelTotal`,
  ADD COLUMN `fuelTrip` double NULL DEFAULT NULL AFTER `fuelRemain`,
  ADD COLUMN `fuelIdle` double NULL DEFAULT NULL AFTER `fuelTrip`,
  ADD COLUMN `fuelPTO` double NULL DEFAULT NULL AFTER `fuelIdle`,
  ADD COLUMN `fuelEngineOn` double NULL DEFAULT NULL AFTER `fuelPTO`,
  ADD COLUMN `engineRpm` int(10) unsigned NULL DEFAULT NULL AFTER `fuelEngineOn`,
  ADD COLUMN `engineOnHours` double NULL DEFAULT NULL AFTER `engineHours`,
  ADD COLUMN `engineLoad` double NULL DEFAULT NULL AFTER `engineOnHours`,
  ADD COLUMN `engineTorque` double NULL DEFAULT NULL AFTER `engineLoad`,
  ADD COLUMN `idleHours` double NULL DEFAULT NULL AFTER `engineTorque`,
  ADD COLUMN `workHours` double NULL DEFAULT NULL AFTER `idleHours`,
  ADD COLUMN `transOilTemp` double NULL DEFAULT NULL AFTER `workHours`,
  ADD COLUMN `coolantLevel` double NULL DEFAULT NULL AFTER `transOilTemp`,
  ADD COLUMN `coolantTemp` double NULL DEFAULT NULL AFTER `coolantLevel`,
  ADD COLUMN `intakeTemp` double NULL DEFAULT NULL AFTER `coolantTemp`,
  ADD COLUMN `brakeGForce` double NULL DEFAULT NULL AFTER `intakeTemp`,
  ADD COLUMN `acceleration` double NULL DEFAULT NULL AFTER `brakeGForce`,
  ADD COLUMN `accelerometerXYZ` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `acceleration`,
  ADD COLUMN `brakePressure` double NULL DEFAULT NULL AFTER `accelerometerXYZ`,
  ADD COLUMN `massAirFlowRate` double NULL DEFAULT NULL AFTER `brakePressure`,
  ADD COLUMN `oilPressure` double NULL DEFAULT NULL AFTER `massAirFlowRate`,
  ADD COLUMN `oilLevel` double NULL DEFAULT NULL AFTER `oilPressure`,
  ADD COLUMN `oilTemp` double NULL DEFAULT NULL AFTER `oilLevel`,
  ADD COLUMN `airPressure` double NULL DEFAULT NULL AFTER `oilTemp`,
  ADD COLUMN `airFilterPressure` double NULL DEFAULT NULL AFTER `airPressure`,
  ADD COLUMN `turboPressure` double NULL DEFAULT NULL AFTER `airFilterPressure`,
  ADD COLUMN `ptoEngaged` tinyint(4) NULL DEFAULT NULL AFTER `turboPressure`,
  ADD COLUMN `ptoHours` double NULL DEFAULT NULL AFTER `ptoEngaged`,
  ADD COLUMN `throttlePos` double NULL DEFAULT NULL AFTER `ptoHours`,
  ADD COLUMN `brakePos` double NULL DEFAULT NULL AFTER `throttlePos`,
  ADD COLUMN `j1708Fault` bigint(20) unsigned NULL DEFAULT NULL AFTER `vBatteryVolts`,
  ADD COLUMN `malfunctionLamp` tinyint(4) NULL DEFAULT NULL AFTER `faultCode`,
  ADD COLUMN `tirePressure` varchar(140) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `malfunctionLamp`,
  ADD COLUMN `tireTemp` varchar(140) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `tirePressure`,
  ADD COLUMN `tankLevel` double NULL DEFAULT NULL AFTER `tireTemp`,
  ADD COLUMN `dayEngineStarts` smallint(5) unsigned NULL DEFAULT NULL AFTER `tankLevel`,
  ADD COLUMN `dayIdleHours` double NULL DEFAULT NULL AFTER `dayEngineStarts`,
  ADD COLUMN `dayFuelIdle` double NULL DEFAULT NULL AFTER `dayIdleHours`,
  ADD COLUMN `dayWorkHours` double NULL DEFAULT NULL AFTER `dayFuelIdle`,
  ADD COLUMN `dayFuelWork` double NULL DEFAULT NULL AFTER `dayWorkHours`,
  ADD COLUMN `dayFuelPTO` double NULL DEFAULT NULL AFTER `dayFuelWork`,
  ADD COLUMN `dayDistanceKM` double NULL DEFAULT NULL AFTER `dayFuelPTO`,
  ADD COLUMN `dayFuelTotal` double NULL DEFAULT NULL AFTER `dayDistanceKM`;

