-- ============================================================
-- Limpieza de columnas sin uso - servidor 66.240.210.125, esquema gts
-- MySQL 5.6.38. Generado 2026-10-06.
-- kmini/odometerini tenían datos en 12 vehículos (movilbus): quedan en device_bak_20261006.
-- Verificado: sin datos, sin referencias en código (D:\Proyectos), sin uso en
-- rutinas/triggers/vistas/eventos de los esquemas dbmtc, essalud, gestion_villa,
-- gts, gtsdesa; sin FKs; sin SELECT * / INSERT sin columnas sobre estas tablas.
-- Reversa: limpieza_columnas_muertas_ROLLBACK.sql
-- ============================================================

USE gts;

-- 0) Respaldo de device (500 filas) por si acaso
CREATE TABLE device_bak_20261006 AS SELECT * FROM device;

-- 1) device: 103 columnas (incluye kmini, odometerini y odometercontrol, el intento anterior de km real) + el índice notifyTime
ALTER TABLE device
  DROP INDEX notifyTime,
  DROP COLUMN `equipmentStatus`,
  DROP COLUMN `vehicleMake`,
  DROP COLUMN `vehicleModel`,
  DROP COLUMN `driverStatus`,
  DROP COLUMN `fuelCapacity`,
  DROP COLUMN `fuelEconomy`,
  DROP COLUMN `planDistanceKM`,
  DROP COLUMN `installTime`,
  DROP COLUMN `resetTime`,
  DROP COLUMN `expirationTime`,
  DROP COLUMN `deviceType`,
  DROP COLUMN `pushpinID`,
  DROP COLUMN `displayColor`,
  DROP COLUMN `simID`,
  DROP COLUMN `ignitionIndex`,
  DROP COLUMN `codeVersion`,
  DROP COLUMN `featureSet`,
  DROP COLUMN `ipAddressValid`,
  DROP COLUMN `lastDuplexConnectTime`,
  DROP COLUMN `pendingPingCommand`,
  DROP COLUMN `lastPingTime`,
  DROP COLUMN `totalPingCount`,
  DROP COLUMN `maxPingCount`,
  DROP COLUMN `commandStateMask`,
  DROP COLUMN `expectAck`,
  DROP COLUMN `expectAckCode`,
  DROP COLUMN `lastAckCommand`,
  DROP COLUMN `lastAckTime`,
  DROP COLUMN `dcsPropertiesID`,
  DROP COLUMN `dcsConfigMask`,
  DROP COLUMN `dcsConfigString`,
  DROP COLUMN `dcsCommandHost`,
  DROP COLUMN `supportsDMTP`,
  DROP COLUMN `unitLimitInterval`,
  DROP COLUMN `maxAllowedEvents`,
  DROP COLUMN `totalProfileMask`,
  DROP COLUMN `totalMaxConn`,
  DROP COLUMN `totalMaxConnPerMin`,
  DROP COLUMN `duplexProfileMask`,
  DROP COLUMN `duplexMaxConn`,
  DROP COLUMN `duplexMaxConnPerMin`,
  DROP COLUMN `lastTcpSessionID`,
  DROP COLUMN `listenPortCurrent`,
  DROP COLUMN `lastOutputState`,
  DROP COLUMN `lastFuelLevel`,
  DROP COLUMN `lastFuelTotal`,
  DROP COLUMN `lastOilLevel`,
  DROP COLUMN `lastDistanceKM`,
  DROP COLUMN `lastIgnitionHours`,
  DROP COLUMN `lastMalfunctionLamp`,
  DROP COLUMN `lastFaultCode`,
  DROP COLUMN `lastNotifyTime`,
  DROP COLUMN `lastNotifyCode`,
  DROP COLUMN `lastNotifyRule`,
  DROP COLUMN `notifyEmail`,
  DROP COLUMN `notifySelector`,
  DROP COLUMN `notifyDescription`,
  DROP COLUMN `notifySubject`,
  DROP COLUMN `notifyText`,
  DROP COLUMN `notifyUseWrapper`,
  DROP COLUMN `notifyPriority`,
  DROP COLUMN `parkedLatitude`,
  DROP COLUMN `parkedLongitude`,
  DROP COLUMN `parkedRadius`,
  DROP COLUMN `assignedUserID`,
  DROP COLUMN `thermalProfile`,
  DROP COLUMN `hoursOfOperation`,
  DROP COLUMN `activeCorridor`,
  DROP COLUMN `fixedLatitude`,
  DROP COLUMN `fixedLongitude`,
  DROP COLUMN `fixedAddress`,
  DROP COLUMN `fixedContactPhone`,
  DROP COLUMN `fixedServiceTime`,
  DROP COLUMN `linkURL`,
  DROP COLUMN `linkDescription`,
  DROP COLUMN `lastBorderCrossTime`,
  DROP COLUMN `maintIntervalKM0`,
  DROP COLUMN `maintOdometerKM0`,
  DROP COLUMN `maintIntervalKM1`,
  DROP COLUMN `maintOdometerKM1`,
  DROP COLUMN `maintIntervalHR0`,
  DROP COLUMN `maintEngHoursHR0`,
  DROP COLUMN `maintNotes`,
  DROP COLUMN `reminderMessage`,
  DROP COLUMN `reminderInterval`,
  DROP COLUMN `reminderTime`,
  DROP COLUMN `lastServiceTime`,
  DROP COLUMN `nextServiceTime`,
  DROP COLUMN `workOrderID`,
  DROP COLUMN `jobNumber`,
  DROP COLUMN `jobLatitude`,
  DROP COLUMN `jobLongitude`,
  DROP COLUMN `jobRadius`,
  DROP COLUMN `lastDataPushTime`,
  DROP COLUMN `lastEventCreateMillis`,
  DROP COLUMN `tiempoorigen`,
  DROP COLUMN `configtime`,
  DROP COLUMN `codmantenimiento`,
  DROP COLUMN `msjpbruscas`,
  DROP COLUMN `msjdesconexion`,
  DROP COLUMN `odometerini`,
  DROP COLUMN `kmini`,
  DROP COLUMN `odometercontrol`,
  ALGORITHM=INPLACE, LOCK=NONE;

-- 2) eventdata: 67 columnas (~470 MB; reconstruye la tabla en línea, DML permitido).
--    Ejecutar en horario de baja carga. Si falla por innodb_online_alter_log_max_size,
--    reintentar con el agente detenido unos minutos.
ALTER TABLE eventdata
  DROP COLUMN `transportID`,
  DROP COLUMN `inputMask`,
  DROP COLUMN `outputMask`,
  DROP COLUMN `seatbeltMask`,
  DROP COLUMN `odometerOffsetKM`,
  DROP COLUMN `geozoneIndex`,
  DROP COLUMN `geozoneID`,
  DROP COLUMN `streetAddress`,
  DROP COLUMN `stateProvince`,
  DROP COLUMN `postalCode`,
  DROP COLUMN `subdivision`,
  DROP COLUMN `speedLimitKPH`,
  DROP COLUMN `isTollRoad`,
  DROP COLUMN `gpsFixStatus`,
  DROP COLUMN `horzAccuracy`,
  DROP COLUMN `vertAccuracy`,
  DROP COLUMN `HDOP`,
  DROP COLUMN `fuelPressure`,
  DROP COLUMN `fuelUsage`,
  DROP COLUMN `fuelTemp`,
  DROP COLUMN `fuelLevel`,
  DROP COLUMN `fuelLevel2`,
  DROP COLUMN `fuelEconomy`,
  DROP COLUMN `fuelTotal`,
  DROP COLUMN `fuelRemain`,
  DROP COLUMN `fuelTrip`,
  DROP COLUMN `fuelIdle`,
  DROP COLUMN `fuelPTO`,
  DROP COLUMN `fuelEngineOn`,
  DROP COLUMN `engineRpm`,
  DROP COLUMN `engineOnHours`,
  DROP COLUMN `engineLoad`,
  DROP COLUMN `engineTorque`,
  DROP COLUMN `idleHours`,
  DROP COLUMN `workHours`,
  DROP COLUMN `transOilTemp`,
  DROP COLUMN `coolantLevel`,
  DROP COLUMN `coolantTemp`,
  DROP COLUMN `intakeTemp`,
  DROP COLUMN `brakeGForce`,
  DROP COLUMN `acceleration`,
  DROP COLUMN `accelerometerXYZ`,
  DROP COLUMN `brakePressure`,
  DROP COLUMN `massAirFlowRate`,
  DROP COLUMN `oilPressure`,
  DROP COLUMN `oilLevel`,
  DROP COLUMN `oilTemp`,
  DROP COLUMN `airPressure`,
  DROP COLUMN `airFilterPressure`,
  DROP COLUMN `turboPressure`,
  DROP COLUMN `ptoEngaged`,
  DROP COLUMN `ptoHours`,
  DROP COLUMN `throttlePos`,
  DROP COLUMN `brakePos`,
  DROP COLUMN `j1708Fault`,
  DROP COLUMN `malfunctionLamp`,
  DROP COLUMN `tirePressure`,
  DROP COLUMN `tireTemp`,
  DROP COLUMN `tankLevel`,
  DROP COLUMN `dayEngineStarts`,
  DROP COLUMN `dayIdleHours`,
  DROP COLUMN `dayFuelIdle`,
  DROP COLUMN `dayWorkHours`,
  DROP COLUMN `dayFuelWork`,
  DROP COLUMN `dayFuelPTO`,
  DROP COLUMN `dayDistanceKM`,
  DROP COLUMN `dayFuelTotal`,
  ALGORITHM=INPLACE, LOCK=NONE;

-- 3) Verificación (conteo de columnas esperado en cada tabla)
SELECT COUNT(*) AS device_cols FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='gts' AND TABLE_NAME='device';   -- esperado: 97
SELECT COUNT(*) AS eventdata_cols FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='gts' AND TABLE_NAME='eventdata'; -- esperado: 27

-- 4) Cuando confirmes que todo funciona (unos días), borra el respaldo:
-- DROP TABLE device_bak_20261006;
